### ISSUE TITLE
Prefer mamba and conda forge channels

### ISSUE THREAD

**Issue by Zaharid** [NNPDF/nnpdf#1284]
The whole issue with #1279 brings to attention that conda forge now has a lot of public documentation, one can see who maintains the recipes and probably so many variations that something like  #1279  would be more apparent. 

On top of that there is the mamba project which solves dependencies a lot faster than conda (which can be borderline unusable). With that I would suggest to update https://github.com/NNPDF/binary-bootstrap/blob/master/bootstrap.sh as well as the CI code and relevant pieces of the documentation  to have conda forge as higher priorities than defaults and use mamba instead of conda.

**Comment by Zaharid** [comment]
@RoyStegeman @scarlehoff what do you think about trying to switch the channel order in ci builds and see how much of a problem that causes. Then there is https://github.com/NNPDF/binary-bootstrap/pull/4 but I suppose I am not sure about the order in which to do various things. including potentially having to ask people to edit their .condarc file.

**Comment by scarlehoff** [comment]
Well, it is becoming increasingly clear that we will need to do this so let's just do it and when people complain things don't work we make a point of asking first to see their `.condarc` file.

**Comment by Zaharid** [comment]
Ok @RoyStegeman could you please make PR switching the order of conda-forge and defaults in various places. Hint:
```
 $ rg --hidden conda-forge
.github/workflows/fitbot.yml
42:        conda config --append channels conda-forge

.github/workflows/tests.yml
41:        conda config --append channels conda-forge

.github/workflows/docker.yml
30:        conda config --append channels conda-forge

n3fit/runcards/nnpdfenv-tag-4.0.4.yml
7:  - conda-forge

n3fit/runcards/reproduce_nnpdf40/nnpdf40_env.yml
6:  - conda-forge

docker/dockerfile
33:RUN conda config --append channels conda-forge                                    && \

doc/validphys2/guide.md
391:`defaults` channel, as well as from the community `conda-forge`
```

If that looks not too terrible I'll merge the binary bootsrap PR.

**Comment by RoyStegeman** [comment]
Yes I was planning to try this over the weekend. Given that switching them locally is fine, hopefully  this should be straightforward (:crossed_fingers: ).

**Comment by AleCandido** [comment]
While exploring for #1564 I found this issue.

I know that this idea might be unpopular, but instead of fiddling too much with Conda channels, or fancy alternatives like Mamba, what about releasing just a "simple" `nnpdf` wheel?

The whole theory pipeline is now wheel based (as the main channel, while Conda is coming piece by piece, thanks to the time spent by @scarlehoff, @scarrazza, and @cschwan), even solving part of the dependency issue (no more APFEL around).
Re `lhapdf`, I already released an obscured named wheel (I don't have the permission of maintainers, even though I proposed them the actual solution), and if it is the only obstacle I can take care of improving that packaging: it's working almost fine for Linux users, even though it has some issues with the setup of the data folder (but it might be solved using `lhapdf-management`) and I guess I can solve the problem of Mac users in a reasonable amount of time (and even Windows ones, if any is around...).
The only issue remaining is `libnnpdf` itself, but this is already been tackled by @scarlehoff with his `destroyng-c++` series.

I've the feeling that a "simple" wheel might really be possible, and `pip install nnpdf` to be accessible for all NNPDF users (but even external users, with no more complications than Conda).
