### ISSUE TITLE
sqrt_covmat does not work for theory_covariance matrix

### ISSUE THREAD

**Issue by andreab1997** [NNPDF/nnpdf#1542]
In order to add the theory_covmat contribution to make_replica, it is necessary to compute its sqrt (using https://github.com/NNPDF/nnpdf/blob/53a145fc86c4f17abf0bf2960900cd6d8aeafe3c/validphys2/src/validphys/covmats.py#L343)
The problem is that sqrt_covmat is failing when used to compute the sqrt of a theory_covmat because the latter is in general not positive definite (although its negative eigenvalues are "relatively small" with respect to its biggest positive eigenvalues)
Is there anyone already aware of this problem?

**Comment by scarlehoff** [comment]
@Zaharid I remember some discussion about this at the time when I joined NNPDF. I guess everyone involved has now moved on but do you know whether there is some piece of code that will allow us to decompose the matrix easily?

(spoiler: richard was right, the covmat was being skipped in the sampling despite the flag being set to true because it was never implemented in `make_replica`)

**Comment by scarlehoff** [comment]
@tgiani Hi Tommaso, do you have any insight on what this problem could actually be?

**Comment by tgiani** [comment]
@scarlehoff hi Juan, uhm I remember that I did work on this yes. I can look into that next week (I am away until tuesday), but maybe the solution was to first add the theory cov mat to the experimental one and then to compute the sqrt of the total covmat you get in this way. In this way you re always computing the sqrt of a positive def matrix. Not sure if thsi was the solution tho, need to look back at the code

**Comment by tgiani** [comment]
so in other words I think you never need to compute the sqrt of the th cov mat itself, only the sqrt of the su exp+th covmat, which is positive definite

**Comment by scarlehoff** [comment]
I see, please check once you get back!

**Comment by tgiani** [comment]
Hi @scarlehoff , in the old c++ code the covmat entering the chi2 definition and the one entering the replicas generation are loaded in these 2 functions

https://github.com/NNPDF/nnpdf/blob/001550dde517f7125a67ed60431c42a51403ba49/libnnpdf/src/experiments.cc#L580

https://github.com/NNPDF/nnpdf/blob/001550dde517f7125a67ed60431c42a51403ba49/libnnpdf/src/experiments.cc#L571

using 

https://github.com/NNPDF/nnpdf/blob/001550dde517f7125a67ed60431c42a51403ba49/libnnpdf/src/chisquared.cc#L34

You see that if there is a theroy covariance matrix, this is loaded here

https://github.com/NNPDF/nnpdf/blob/001550dde517f7125a67ed60431c42a51403ba49/libnnpdf/src/chisquared.cc#L93

and added to the experimenatal contribution of the total theory cov. There are no problems in computing the sqrt of this matrix, becasue it is the total exp+th cov mat, which is positive def as long as the exp cov mat is positive def.

In the case of the covmat enetring the chi2 definition there is nothing else to do, it is loaded here
https://github.com/NNPDF/nnpdf/blob/001550dde517f7125a67ed60431c42a51403ba49/libnnpdf/src/experiments.cc#L582

and used to compute the chi2.

In the case of the replicas generation, it is loaded here 
https://github.com/NNPDF/nnpdf/blob/001550dde517f7125a67ed60431c42a51403ba49/libnnpdf/src/experiments.cc#L573

without accounting for the multiplicative uncertainties (you see that the corresponding input is set to false). 
The reason for this is that the replicas distribution is not really gaussian, but the product of two gaussians (one for the central value and one for the normalization). The theory cov mat is considered as part of the gaussian error of the central values, and therefore it is summed to the component of the exp covmat coming from additive uncertainties.
The the function MakeReplica
https://github.com/NNPDF/nnpdf/blob/001550dde517f7125a67ed60431c42a51403ba49/libnnpdf/src/experiments.cc#L144

samples the central values using the loaded th+exp cov matrix (where only the contribution from the additive uncertainties is considered)
https://github.com/NNPDF/nnpdf/blob/001550dde517f7125a67ed60431c42a51403ba49/libnnpdf/src/experiments.cc#L188
and also perform a separate gaussian sampling for the normalization of each datapoint
https://github.com/NNPDF/nnpdf/blob/001550dde517f7125a67ed60431c42a51403ba49/libnnpdf/src/experiments.cc#L210
so that at the end you get a replica sampled according to the desired distribution which also include the th cov mat contribution

**Comment by tgiani** [comment]
I don t know if this is clear and I m not sure what is done atm in ```n3fit```. Maybe I can help with this? We can discuss later at the code call

**Comment by scarlehoff** [comment]
So if I understand correctly the old code did:

d_{art} = (d_{cv} + r*(covmat_add + covmat_theory)) * (1 + multiplicative) 

???

> I don t know if this is clear and I m not sure what is done atm in n3fit. Maybe I can help with this? We can discuss later at the code call

It is, I think it confirms what we think (and we think it is wrong ...) 

In `n3fit` up to now we were using the `nnfit ` `MakeReplica` but now that we have moved to `vp` we need to modify it.
What @andreab1997 is doing is just 

d_{art} = d_{cv} + r*(full_covmat)

so that the covmat that generates the replica is equal to the covmat that is using for the fit. Sadly anything else that we try is problematic in some sense or another.

I'm surprised you didn't have a problem with negative eigenvalues though (or rather, -0 eigenvalues), they seem to be there. Our guess is that the iterative procedure used by `gsl` just happen to converge before arriving to a situation in which they would be a problem while `numpy` explicitly checks before computing the cholesky decomposition.

**Comment by tgiani** [comment]
yes I think this is what the old code does
```d_{art} = (d_{cv} + r*(covmat_add + covmat_theory)) * (1 + multiplicative)```
which should be something distributed according to the product of two gaussians, which is what reported in the old nnpdf papers.
This other thing ```d_{art} = d_{cv} + r*(full_covmat)``` is a gaussian distribution, which is fine but not what you get if you have multiplicative uncertainties I think.
Not sure which negative eigenvalues you are referring to tho. With the old code you are always inverting a positive matrix. Which matrix are you inverting in n3fit? I think that also in the old code there is a check for the positivity of the matrix before using cholesky

**Comment by scarlehoff** [comment]
We are inverting covmat_exp + covmat_th (the negative eigenvalues are the same with and without multiplicative). We find many negative eigenvalues with covmat_th alone and a few (10 out of 2000) with the sum. These are of the order `10^{-6}` (and we removed it by bumping the diagonal of the th_covmat by that amount).

**Comment by tgiani** [comment]
uhm it s strange. I think th cov mat is positive semi definite by construction, so you can have eigenvalues which are 0, and so you will not be able to invert it, but you shouldn t be getting any negative ones. The exp one is positive definite (and this is checked explicitly in buildmaster) so the sum should be positive as well. Are you using the same th cov mat as in the NNPDF3.1 paper or something different?

**Comment by scarlehoff** [comment]
Well, 0 and `-1e-8` are basically the same (in pratice we are getting eigenvalues that are `1e10` and `-1e2`, so the negatives ones are 8 orders of magnitude below so might be just numerical 0s (but enough non 0 for `numpy` to pick it up).

As far as we know, we are using the same covmat as in the NNPDF3.1 paper, if the code hasn't changed in the meanwhile.

**Comment by tgiani** [comment]
I see. As for the sampling with or without multiplicative error, this is something which was decided after long discussions I don t fully remember, so It might be worth mentioning it during some phone call to see what people think/remember. Personally I don t see why what done previously should be wrong, but of course I could be missing something

**Comment by scarlehoff** [comment]
In my view, the multiplicative error makes sense as applied directly to the data so

d_{art} = d_{cv}* (1 + multiplicative) + r*(covmat_add + covmat_theory)

I could accept it also on the additive error because well "we choose a situation in which the cv is a different one" so that's ok but I don't think it should be ever applied to the theory error because it is totally independent of it (and for the chi2 it is added in quadrature to the covmat that includes both additive and multiplicative).

But, in more practical terms, when we do it as it was done in vp we get a terrible `postfit` situation with a lot of outliers.

**Comment by tgiani** [comment]
I guess that it s a matter of the assumptions we are making. If we say that we have two gaussian variables which are the cv and the normalization, then we should sample the first and the second according to the respective gaussian distributions, right? And if we say that the theory error is additive than I think we get the equation of the old code

**Comment by scarlehoff** [comment]
It seems we have solved the problem: https://github.com/NNPDF/nnpdf/pull/1528/files/f1c514a95bbeacca3ce8ddf126d269ea2e740d01..d43b3577e94e99902df425b35e95d2ba0e76ae98

The ordering of the dumping of the covmat changes depending on whether you use `bigexp` or order by process, which means that if it is read blindly the result also changes.

This was a bit of a pain to find due to the processes `DIS NC` and `DIS CC` which `nnfit` reads as two different columns (which meant I was also getting negative eigenvalues in `nnfit` but they were different from `validphys` -the positive big ones were the same-).
Turns out if you use `BIGEXP` everything works but if you order by process then it only works if you runcard happens to keep the same order.

Luckily the solution is trivial and just by reordering the `DataFrame` the right result is obtained.

imho the right solution is to make the experimental covmat _also_ into a `DataFrame` (I'm not a fan of `pandas` but at this point is the only quantity that is not a `DataFrame`) but I would do that afterward. I'm happy I can close this and remove the 20GB or whatever of covmats that I've saved in my computer.
