### ISSUE TITLE
Kfactors for compound datasets

### ISSUE THREAD

**Issue by giacomomagni** [NNPDF/nnpdf#1672]
While trying to implement new `k-factors` files I found a potential bug.
`CF` files with the new `FK tables` naming convention are not correctly loaded from the `ymldb` in case of compound observables. 
In particular in [loader.py](https://github.com/NNPDF/nnpdf/blob/bea644cfb02086d6f8ae2ffe9f660a6f9d5f5d0e/validphys2/src/validphys/loader.py#L376--L385)  `CF` names should be read from `'operands'` and not `'target_dataset'`.

I propose the following fix:
```
        cfac_name = metadata["target_dataset"]
        # check whether there is a compound file
        cpath = theory.path / "compound" / f"FK_{cfac_name}-COMPOUND.dat"
        if cpath.exists():
            # Get the target filenames
            tnames = [i[3:-4] for i in cpath.read_text().split() if i.endswith(".dat")]
            cfactors = [self.check_cfactor(theoryID, i, cfac) for i in tnames]
        else:
            cfac_name = metadata["operands"]
            cfactors = []
            for operand in cfac_name:
                for fk_tab in operand:   
                    cfactors.append(self.check_cfactor(theoryID, fk_tab, cfac))
        ###
```

I suggest to deprecate or raise an error or a warning when the the folder `compound` is still present in a theory following the new naming convention, as this can lead to potential inconsistencies.

**Comment by scarlehoff** [comment]
> CF files with the new FK tables naming convention

We should indeed talk about this next week... higher order cfactors we have agreed they will be absorbed into the fktables, so new theories should not have them (so, no new cfactors should be created).

But it might be that we still want to be able to apply _some_ cfactors and then we would need something like you propose. Please remember to raise this issue during the CM!

**Comment by Zaharid** [comment]
Cfactor support should be maintained and should be per-fktable. 

I think we should used them much less though. In particular, I think they are best used for corrections that are *not* to be included by default. Overall cfactors have the advantage that they are very prominent in the runcard and easy enough to debug and look at. The disadvantages are that  they are easy to forget and are somewhat clunky to use in vp, namely that e.g. comparing nnlo vs nlo requires duplicating the dataset definitions one time with the cfactors and another without (largely because we never got around to implementing the "defaults" functionality).

For example ITSTM the benefit for having a separate QCD cfactor for nnlo is much smaller than the cost of forgetting them from time to time and having to do unplesant tricks with vp comparisons . That said, last time I heard this mentioned I think @enocera had a different opinion on this point, so it would be good to agree on that.

**Comment by enocera** [comment]
To make my opinion clear: I agree with @scarlehoff about incorporating `QCD` K-factors into FK tables. But we want to preserve the possibility of having K-factors to quickly test for other corrections (e.g. resummation).
