### ISSUE TITLE
Runcards using theoryid 400?

### ISSUE THREAD

**Issue by APJansen** [NNPDF/nnpdf#1727]
I want to use theoryid 400, but there are no example runcards with it. I can simply change it, for example in the Basic_runcard, but then on running `vp-setupfit Basic_runcard.yml it doesn't find the file `theory_400/yamldb/NMCPD_dw.yaml`.
I'm guessing because this is no longer used? 
Can I find runcards appropriate for theory 400 anywhere?

**Comment by RoyStegeman** [comment]
I think replacing `NMCPD_dw` with `NMCPD_dw_ite` should allow you to run `n3fit` in this case. Having said that, why do you want to use theory 400 instead of 200? They correspond to the same theory settings but theories 400 and beyond have been produced with the new codes (yadism, eko, etc.) and we don't guarantee them to be stable as development is still ongoing (in fact, I believe that currently none of the theories 401+ would work).

**Comment by APJansen** [comment]
Thanks, that did fix it.
The reason was that @scarlehoff advised us to, to avoid using the legacy dataloader. But if that's the case I can stick to 200.

**Comment by scarlehoff** [comment]
No, you should use theory 400. Otherwise you will be using the `pineappl` reader.

As @RoyStegeman said, that change will allow you to use theory 400 with the Basic Runcard. All datasets from this runcard  https://github.com/NNPDF/nnpdf/blob/master/n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01180_1000.yml are available in theory 400 so you can pick a few from there to test. There's nothing special in the Basic Runcard, they are just a few dataset chosen at random.

**Comment by Radonirinaunimi** [comment]
The reason is to be able to use the pineparser and not rely on the legacy reader which contains some memory issues especially related to #1661. I believe that for the investigation purposes Aaron is doing, this would not be a problem.

**Comment by RoyStegeman** [comment]
Okay so theory 400 should be used, but making sure to use only datasets available with the theory.
