### ISSUE TITLE
some cfactors missing in theory 400

### ISSUE THREAD

**Issue by comane** [NNPDF/nnpdf#1730]
@scarlehoff , @Zaharid , @RoyStegeman  After creating a new conda environment for nnpdf=4.0.6, running
`inp = {
    "fit": "210713-n3fit-001",
    "dataset_inputs": {"from_": "fit"},
    "use_cuts": "internal",
    "theoryid": 400
}`
`API.data(**inp)`

produces the following error:

ConfigError: Could not find cfactor 'MAS' for FKTable NTVNBDMNFe in theory 400.

After copying the above cfactor in theory 400 from theory 200, I get the same error but for a different cfactor (which I couldn't find in theory 200)
ConfigError: Could not find cfactor 'QCD' for FKTable DYE886R in theory 400

As a note: I did not have this error before (in the previous conda environment which had a different nnpdf), and the theory folder is the same. So it is probably related to the fact that something is calling the files.

**Comment by scarlehoff** [comment]
Does your theory 400 contain a "compound" folder?

**Comment by comane** [comment]
No it doesn't

**Comment by RoyStegeman** [comment]
It's probably just that version 4.0.6 does not support the current theory format. Why do you want to use theory 400 with 4.0.6 specifically?

**Comment by scarlehoff** [comment]
Ah, missed the 4.0.6 mention.

Indeed, new theories only work with master.

**Comment by comane** [comment]
I see thanks, in that case I could probably just add those cfactors manually. Do you know where to find CF_QCD_ DYE886R?

**Comment by RoyStegeman** [comment]
You should probably just use theory 200 instead.

**Comment by comane** [comment]
The thing is that I need uniform xgrids for the fktables, hence, theory 400 is needed

**Comment by RoyStegeman** [comment]
You could try theory 424, that one may correspond to the reader at the time of 4.0.6

**Comment by comane** [comment]
Thank you for the suggestion. I tried, however, I am getting the same error as for theory 400

**Comment by scarlehoff** [comment]
So, I stand by what @RoyStegeman said. New theories should not be used yet. Theory 399/400 are the only ones that I test more or less regularly to make sure they are in track with master. I think they are stable enough now that I will propose to tag the code (all codes, also eko) once the photon get merged.

However, since I was afraid that someone might have been using one of the old version of the theories I kept a few backups of theories 400 in the theory server together with the others, you can download them manually  https://www.wiki.ed.ac.uk/pages/viewpage.action?spaceKey=nnpdfwiki&title=Storage+servers
