### ISSUE TITLE
Restore theory 500

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1796]
Since 400 might go back to being "non-displaced" but the QED paper might use the displaced threshold, it might be good to restore theory 500 as the one with the displaced threshold.

If you (@enocera @RoyStegeman) are ok with this, I can do so (by copying the current theory 400 as theory 500)

**Comment by RoyStegeman** [comment]
Isn't it more convenient to keep the current theory 400 as it is and make numerical FONLL theory 450 (or whatever is still available)?

**Comment by enocera** [comment]
@scarlehoff Why not just defining a new ID for the theory that uses nFONLL?

**Comment by enocera** [comment]
Exactly same though as @RoyStegeman at exactly the same time.

**Comment by scarlehoff** [comment]
I thought of restoring theory 500 since the reference fits for the QED were run with theoryid: 500 and I've gotten a few questions from different people about which one is 500 :P

But ok, I'm also fine with that. Then what I'll do is update the baseline fit (`230309-ern-002`) to say (and use) theory 400 in the runcard. Is that ok?

**Comment by RoyStegeman** [comment]
> and I've gotten a few questions from different people about which one is 500 :P

Since I was among them, I was happy to just have it confirmed that 500 had become 400. If you move theory 400 you'll get people asking the same about 400, or just use it assuming theory 400 is the same as they see in a report while it may in fact have changed between now and a few weeks/months. Of course that's a risk we'll run into now as well, if people find `230309-ern-002` by the time theory 500 is no longer empty but used for something else (maybe nFONLL), however way fewer fits have 500 in the runcard than 400.

> Then what I'll do is update the baseline fit (`230309-ern-002`) to say (and use) theory 400 in the runcard. Is that ok?

That's probably a good idea. To avoid problems we want to erase `230309-ern-002` from memory :)

**Comment by RoyStegeman** [comment]
> Exactly same thought as @RoyStegeman at exactly the same time.

Great minds think alike ;)

**Comment by enocera** [comment]
I agree with @RoyStegeman's suggestions and with @scarlehoff's plan. Thanks.

**Comment by scarlehoff** [comment]
Done.
