### ISSUE TITLE
`vp-setupfit` with theory covmats

### ISSUE THREAD

**Issue by giacomomagni** [NNPDF/nnpdf#1822]
Both @andreab1997 and myself are experience that `vp-setupfit` takes hours to compute the theory covmat. 

For instance in a global fit the, on the Nikhef cluster on a single core: 
* `7point` takes order of 2-3 hours.
* `n3lo ihou` (70 theories) takes order of 15 hours. 

Since `vp-setupfit` without theory covmat is instantaneous, we were wondering if anyone knows what is the actual bottleneck in constructing the theory covmat. 

* Is it jus loading Fk tables? 
* The log is not really explicative, what is happening during this time ?
* Is there a specific check that slows down the procedure? 
* Can `--parallel` help ? 

Maybe @scarlehoff  @comane have some hints ...

**Comment by scarlehoff** [comment]
I don't remember right now what the problem was, but you are loading all theories from all fktables and computing the predictions (that will take some time and use a lot of memory).

So make sure you have enough memory to load all of them, otherwise it will start using the swap as disk and that will multiply the time it takes. Then after you load everything I don't remember right now but there might be the inversion as well.

I'd suggest doing a test with 8 cores (and 8 times whatever amount of memory you were using) and see what happens. It is likely that parallel doesn't help here because it's probably a memory issue.

If the test works for NNLO (and it goes down to 30m/1h, I don't think you can get much below that but depends on the cluster) increase greatly the memory for n3lo and cross your fingers...

**Comment by giacomomagni** [comment]
Okay I see, but now I have a technical question. 
To submit jobs on the nikhef cluster I'm using `qsub`,  and we possible have infinity memory/CPU. 
Now, how do I run `dask scheduler` there ? Shall I just prepend the 2 commands suggested [here](https://docs.nnpdf.science/tutorials/reportengine_parallel.html) to my bash script ?

I have not tried yet, but seems something that will not work..

**Comment by scarlehoff** [comment]
>  and we possible have infinity memory/CPU.

Do you really have infinite memory? Because if you do then 2/3 hours is way too much. Can you give me a runcard so that I can debug that? 
If you really have infinite memory then there might be a bug (or an unwanted feature). It might also be that at some point we started storing the fktables for far too long or something.

>  Now, how do I run dask scheduler there ?

Which cluster type is this? If this is included here https://jobqueue.dask.org/en/latest/howitworks.html you can use dask jobqueue to generate the scheduler.

If not, if the separate jobs have access to the node you submit from you can always leave a tmux or screen session open with the scheduler.

**Comment by giacomomagni** [comment]
> Do you really have infinite memory? 

I'm requiring 64gb, but in principle can go up to 1tb, if this help. 
 
> Which cluster type is this? If this is included here https://jobqueue.dask.org/en/latest/howitworks.html you can use dask jobqueue to generate the scheduler.

Yes it should use PBS so this might help, thanks for the reference!

**Comment by scarlehoff** [comment]
64gb should be more than enough for 7 theories... there might be something else wrong then :/ (either that or 2/3 hours is the minimun, which would be worse)

**Comment by giacomomagni** [comment]
well let's see if `jobqueue` can mange to speed it up otherwise this step will win the title of "Bottleneck of the THu fit pipeline" as computing the slower Eko jet takes only 3 hour... 

(But you might argue that eko jets have to be computed at least 3 times, so don't worry that might win in any case...)

**Comment by scarlehoff** [comment]
well, if it is still very slow send me one of the (NNLO) runcards because for sure it was a bit faster in the past. It might well be that the computer in Milan is faster than the cluster, but there might also be a bug.
