### ISSUE TITLE
Stopping in hyperopt

### ISSUE THREAD

**Issue by goord** [NNPDF/nnpdf#1840]
It seems that when a stopping condition is triggered in a fold at hyper-optimization, this skips the entire trial (model_trainier.py, 943):
```python
if passed != self.pass_status:
    log.info("Hyperparameter combination fail to find a good fit, breaking")
    # If the fit failed to fit, no need to add a penalty to the loss
    break
```
I would expect that this information is given to the hyper-optimizer, probably in the form of high hyper-losses for the k-folds. When hyperoptimizing with many replicas, the chance for one of them triggering the stopping and invalidating the fit becomes large and results in many discarded trials.

**Comment by scarlehoff** [comment]
Just remove this. This made sense when doing one replica per fold because if it failed to fit then it failed. There was no in-between.
Now with many replicas you might want to maybe have a measure of a given % passing or something.

**Comment by RoyStegeman** [comment]
This has been changed to only cancel the trial if not a single replica for a given fold has found a solution that passes all requirements.

https://github.com/NNPDF/nnpdf/blob/06f7d46c45a02aa6788cb4c9d2992555e4117e29/n3fit/src/n3fit/model_trainer.py#L742-L744

I think this is sensible default behaviour. We could think of making this a parameter that is exposed in the runcard since we know that for e.g. NNPDF4.0 the "failure rate" is of the order 2%, so if we wish to hyperopt for a similar dataset we can reasonably set the threshold for an acceptable failure rate to somewhere around 95%.
