### ISSUE TITLE
Add 3FNS  in default grids.

### ISSUE THREAD

**Issue by giacomomagni** [NNPDF/nnpdf#1856]
Would it be possible to switch to a default grid in the evolution that starts from 1 GeV ?
we should just adopt this grid as default: 

https://github.com/NNPDF/nnpdf/blob/ce6c05cacec95dee36c577503c9a1109daa2908a/n3fit/src/evolven3fit_new/utils.py#L67

and change these lines:

https://github.com/NNPDF/nnpdf/blob/ce6c05cacec95dee36c577503c9a1109daa2908a/n3fit/src/evolven3fit_new/utils.py#L188-L194

This way all the uploaded fits, will automatically include IC in 3FNS and there is no need to do further work. 

Thanks. 

@RoyStegeman , @andreab1997 @scarlehoff

**Comment by scarlehoff** [comment]
What do you mean exactly by this?
In principle the grid is defined by the eko in the theory. So you mean that, when creating the evolution eko for the theory, you would like to have another option available, right?

Theories below < 400 should all have ekos that start at Q=1.65 GeV

For theories above, the ekos can be updated to use Q=1 GeV as the starting evolution and that won't be a problem.

Of course I would be in favour of having a `--qgrid_option grid_option_N` with several defaults to choose from.

**Comment by RoyStegeman** [comment]
In what case would those grids even be used? Looking at where `generate_q2grid` is called it will be used if there is a theory without an eko.tar in the folder. One perhaps strange thing is that it looks like the `Q0` from the theory will be ignored if `Qfin` and `Q_points` are not passed. 

Either way, I don't really understand why those specific grids were defined the way they are  (maybe @scarlehoff does) so for me it's fine if both the nf=4 and nf=3 are the same default grids starting from 1 GeV.

**Comment by scarlehoff** [comment]
The grids were defined to exactly reproduce the grids used in the fits in NNPDF4.0 (and those need to be kept of course since we often want to reproduce NNPDF4.0). 

>  if there is a theory without an eko.tar in the folder

Given how slow generating ekos is, there should be none (and maybe we should remove that option altogether).

> for me it's fine if both the nf=4 and nf=3 are the same default grids starting from 1 GeV.

I would not change any defaults because it already took some tuning to be able to reproduce 4.0 and I would like to really substitute `evolven3fit` by `evolven3fit_new` and remove apfel.

**Comment by giacomomagni** [comment]
My point is to have all the `lhapdf` sets that we produce including already the FFNS `nf=3`. 
So I believe people use `evolven3fit_new` to generate the ekos that goes inside each theory,
if we extend the default grid to include some points also below the charm mass we are done!

This will not change at all the 4.0 reproducibility as the new set will be exactly as the old one, but with some additional Q2

**Comment by scarlehoff** [comment]
> My point is to have all the lhapdf sets that we produce including already some point in the nf=3 scheme.

But this is automatically done if the eko in the theory includes it. And honestly, eko is in constant development (which is a good thing) but that means that I'd rather have "extra options" to do more stuff rather than absorbing defaults.
The people generating theories can add a `--use_grid_nf=3` to their scripts without affecting what some external use could get while mindlessly using our code.

(even more taking into account that the region Q=1 to 1.65 is precisely something that can eventually be inspected by people given the IC papers)

> This will not change at all the 4.0 reproducibility as the new set will be exactly as the old one, but with some additional Q2

For starters it would change how extrapolation works (because there would be a grid below). I want to remove apfel, but I want to be very careful about it.

**Comment by giacomomagni** [comment]
> But this is automatically done if the eko in the theory includes it. And honestly, eko is in constant development (which is a good thing) but that means that I'd rather have "extra options" to do more stuff rather than absorbing defaults. 


Sure but what is the automatic tool to generate these ekos, if not `evolve_n3fit produce_eko ...` ??

> The people generating theories can add a `--use_grid_nf=3` to their scripts without affecting what some external use could get while mindlessly using our code.

Most likely people will forget about it, and then someone else has to generete these additional points...

> For starters it would change how extrapolation works (because there would be a grid below). I want to remove apfel, but I want to be very careful about it.

That would be even and Improvement!! As it is now the 4.0 lhapdf below 1.65 do not make sense!

In any case, if you don't want to have it as default okay...

**Comment by scarlehoff** [comment]
> In any case, if you don't want to have it as default okay...

Until all theories used for NNPDF4.0 don't have their ekos generated and stored in the theories I would very strongly leave the defaults frozen... precisely because:

> Most likely people will forget about it

and they will be generated wrongly. I'd rather have the small inconvenience of having to generate them twice now when people forget.
