### ISSUE TITLE
Missing features and/or issues with plotting in the new commondata

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/nnpdf#1909]
**Potential issue (?)**

When data-theory comparisons are chosen to be plotted as a function of $Q^2$ (ie `x: k2` in the old and `plot_x: Q2` in the new format), the $x$-axis is actually $Q$ (see for example [NMC](https://vp.nnpdf.science/YV7J7VFNQI-WE2btFduADA==/matched_datasets_from_dataspecs17_dataset_report_report.html)). However, in the new commondata, the $x$-label and its unit are read from:
```yaml
Q2: { description: "virtuality", label: "$Q^2$", units: "$GeV^2$" }
```
and therefore the labels and units shown are wrong. Unfortunately, I don't have an example of this for the unpolarised case as the new commondata PR for DIS does not exist yet. I can provide an example for the polarised case if needed.

**Missing feature (?)**

As it stands right now, I don't think the current plotting can support the key `line_by` which is mainly needed for DIS datasets, eg. [HERACOMB](https://vp.nnpdf.science/YV7J7VFNQI-WE2btFduADA==/matched_datasets_from_dataspecs15_dataset_report_report.html) and [NMC](https://vp.nnpdf.science/YV7J7VFNQI-WE2btFduADA==/matched_datasets_from_dataspecs17_dataset_report_report.html).

**Comment by scarlehoff** [comment]
This is a combination of problems.
For the Q2 part (and any other variables), the problem is that for validphys, everything that is `DIS_<any>` becomes `DIS` but we are differentiating that.
The changes I am doing while porting might fix some of this (I'm just doing if `proc_type[:3]==DIS, then DIS` like it is done in a few places already).

With respect to the `line_by`, this was a bug in the reader which hopefully is fixed (it is for the ported dataset, it might not be for anything that is not configured exactly in the same way as the old commondata is... but we'll fix that little by little I guess).

**Comment by scarlehoff** [comment]
This _seems_ to be supported now. At least all 4.0 datasets seem to work alright in the current form. There were a few more cases like the `proc_type[:3] == DIS` that I've mentioned before.

**Comment by Radonirinaunimi** [comment]
Thanks! I have tested all combinations of plotting configurations (including some subtle ones) and everything works fine.
