### ISSUE TITLE
Rework the theory index

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/nnpdf#1938]
It's no secret that the theories indices are a mess.

If we want to keep using integers, we could start using something in the range of 100 000

Where the first 3 digits define the theory type like until now, and the other three 000 are variations of the same. I think 1000 variations per theory is quite safe.

**Comment by RoyStegeman** [comment]
I like this idea, the only potential issue I see is that there are currently less than 200 integers left for the first three digits, though of course they'll fill up much slower this way.

Do you have any thought on how to define the "theory type"? I imagine you mean using the last three digits for e.g. the MHOU variations or alphas variations, that way grouping them under a single theoryID with the first three digits. However, since we can vary along different axes/theory parameters, i.e. a theory with mu_r=mu_f=1 and alphas=0.118 would be part of at least the group of theories that vary alphas and the MHOU theories for the fixed value of alphas. 

It's not so much that I want to keep use integers, it's just that I'm pretty sure they need to be. We certainly don't have complete freedom because I remember with nFONLL I wanted to do something like 700a, 700b, etc, for the sub-theories but some code was expecting integers. Perhaps it's not a huge effort to let go of this constraint, but I'm not sure using strings of floats would resolve our issue.

**Comment by scarlehoff** [comment]
> Do you have any thought on how to define the "theory type"? 

Not at all. And there will still be some problems  "oh, crap, I put scale variations between 100120 and 100129 and someone took 100130, but I need a new scale variation that will now be 100145"

But at least it will be clear that they are all 100-theories.

> I see is that there are currently less than 200 integers left for the first three digits,

to be completely fair, way more than 50% of the theories in the server from 200 onwards are redundant. Everything between 300 and 700 could be removed other than the test theories or th 600-610.

**Comment by RoyStegeman** [comment]
Ah so type would be NNPDF releases, i.e. NNPDF3.1 family and the NNPDF4.0 family. So once we start working towards NNPDF4.1 that would get it's own first three digit ID, and side projects such as polarized also get their own first three digits. I suppose that could indeed work

> way more than 50% of the theories in the server from 200 onwards are redundant

Ah that's also true

**Comment by Radonirinaunimi** [comment]
> It's no secret that the theories indices are a mess.
> 
> If we want to keep using integers, we could start using something in the range of 100 000
> 
> Where the first 3 digits define the theory type like until now, and the other three 000 are variations of the same. I think 1000 variations per theory is quite safe.

I think this is indeed a sensible idea.

> to be completely fair, way more than 50% of the theories in the server from 200 onwards are redundant. Everything between 300 and 700 could be removed other than the test theories or th 600-610.

Probably not 397, we still want to have that at hands just in case.
