### ISSUE TITLE
Latest conda install of nnpdf missing files?

### ISSUE THREAD

**Issue by LucianHL** [NNPDF/nnpdf#2155]
I am looking to play around with apfelcomb (which I believe is now the way to produce FK tables?) but installing the latest nnpdf code in the usual way:

conda create -n test
conda activate test
conda install nnpdf

is not leading to various header files ('NNPDF/...') and libraries ('libnnpdf') being installed. Looking at the corresponding .json file in conda-meta/ these are indeed missing there. I can get something to work - or at least for apfelcomb to compile after manually changing some std flags - by instead installing

conda install nnpdf=4.0.6.1188

which is a version I have used previously and does have these headers etc. Probably that is fine, but just to raise this in case I am missing something.

**Comment by scarlehoff** [comment]
Hi @LucianHL we actually stopped using apfelcomb, since we moved to a pipeline based on EKO and PineAPPL: https://inspirehep.net/literature/2635876

and what used to be `apfelcomb` is now `pineko`: https://github.com/NNPDF/pineko

If you absolutely need to use apfelcomb, you will need an older version of nnpdf (4.0.6 -> 4.0.7 is where this change happened indeed).

The documentation needs to be updated to reflect all this, which is something we hope to be able to do before the next release (hopefully in the next few months).
I don't know whether you are starting from PineAPPL grids or applgrid tables but in any case, a "easy, from scratch to fktable" tutorial would be good to have, I just added an issue about that: https://github.com/NNPDF/pineko/issues/196

**Comment by LucianHL** [comment]
Hi @scarlehoff - thanks a lot! No particular desire on my side to use `apfelcomb`, I was indeed just following the documentation. 

I am starting from applgrids (or potentially fastnlo grids), basically just looking to convert some of our own grid files to FK tables in order to do some closer comparisons. Is there any particular issue in using apfelcomb with that in meantime can I ask? I will give `pineko` a go though.

**Comment by scarlehoff** [comment]
No, the code can handle both old (apfelcomb) and new (pineko) versions of the fktables. The old ones are just heavier and less versatile but other than that is fine.

Pineko works with pineappl grids, but pineappl can convert both fastnlo and applgrids to its own format so it should be fine.

**Comment by felixhekhorn** [comment]
Hi @LucianHL ,
1. to convert APPLgrids or fastNLO tables to PineAPPL grids take a look to the `pineappl import` command. I'm not sure the two features are active by default, but it case no you can check it [here](https://nnpdf.github.io/pineappl/docs/installation.html#optional-applgrid-exporterimporter).

2. once you have PineAPPL grids, you can use `pineko` to upgrade them to FK table

please feel free to open an issue on either of these repos if you have more questions

**Comment by LucianHL** [comment]
Ok great, thanks both I will try that!
